# Generated by Django 4.2.11 on 2024-04-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_imgage',
            field=models.ImageField(blank=True, null=True, upload_to='static/vege/img'),
        ),
    ]
