# Generated by Django 4.2.11 on 2024-04-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_receipe_receipe_imgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='receipe_imgage',
            new_name='receipe_image',
        ),
    ]
