# Generated by Django 4.2.11 on 2024-04-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
