# Generated by Django 4.2.11 on 2024-04-28 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_alter_department_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='departement',
            new_name='department',
        ),
    ]
