# Generated by Django 4.2.11 on 2024-05-02 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_subject_subjectmarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_code']},
        ),
    ]
